In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn import datasets


iris=datasets.load_iris()

In [2]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
df['flower']=iris.target
df['flower']=df['flower'].apply(lambda x:iris.target_names[x])
df[47:50]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   

    flower  
47  setosa  
48  setosa  
49  setosa

In [4]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(iris.data,iris.target,test_size=0.3)

In [5]:
model=SVC(kernel='rbf',C=30,gamma='auto')
model.fit(Xtrain,ytrain)
y_pred=model.predict(Xtest)


In [6]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_pred)

0.9555555555555556

In [7]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [17]:
kernels=['rbf','linear','poly']
C=[1,10,20]
avg={}
for k in kernels:
    for c in C:
        sv_score=cross_val_score(SVC(kernel=k,C=c,gamma='auto'),iris.data,iris.target,cv=5)
        avg[k+'_'+str(c)]=np.average(sv_score)
avg

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'poly_1': 0.9666666666666666,
 'poly_10': 0.9666666666666666,
 'poly_20': 0.9533333333333334}

# GridSearch

Grid Search uses a different combination of all the specified hyperparameters and their values and calculates the performance for each combination and selects the best value for the hyperparameters. This makes the processing time-consuming and expensive based on the number of hyperparameters involved.

In [26]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(SVC(gamma='auto'),{
    'C':[10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)


GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['rbf', 'linear']})

In [28]:
grid.fit(iris.data,iris.target)


{'mean_fit_time': array([0.        , 0.        , 0.00166302, 0.00160141, 0.0016027 ,
        0.        ]),
 'std_fit_time': array([0.        , 0.        , 0.00272015, 0.00320282, 0.00320539,
        0.        ]),
 'mean_score_time': array([0.00279059, 0.00372243, 0.        , 0.        , 0.        ,
        0.        ]),
 'std_score_time': array([0.00558119, 0.00569486, 0.        , 0.        , 0.        ,
        0.        ]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'

In [30]:
grid_df=pd.DataFrame(grid.cv_results_)
grid_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000000      0.000000         0.002791        0.005581      10   
1       0.000000      0.000000         0.003722        0.005695      10   
2       0.001663      0.002720         0.000000        0.000000      20   
3       0.001601      0.003203         0.000000        0.000000      20   
4       0.001603      0.003205         0.000000        0.000000      30   
5       0.000000      0.000000         0.000000        0.000000      30   

  param_kernel                         params  split0_test_score  \
0          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
2          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 30, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.900000           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.900000           0.933333                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.900000                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.973333        0.038873                2  
2         0.966667        0.036515                3  
3         0.966667        0.042164                4  
4         0.960000        0.038873                5  
5         0.960000        0.048990                5

In [32]:
grid_df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf         0.980000
1      10       linear         0.973333
2      20          rbf         0.966667
3      20       linear         0.966667
4      30          rbf         0.960000
5      30       linear         0.960000

In [33]:
dir(grid)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [34]:
grid.best_score_

0.9800000000000001

In [36]:
grid.best_params_

{'C': 10, 'kernel': 'rbf'}

In [44]:
from sklearn.model_selection import RandomizedSearchCV
RS_cv=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

In [45]:
RS_cv.fit(iris.data,iris.target)
df1=pd.DataFrame(RS_cv.cv_results_)[['param_C','param_kernel','mean_test_score']]
df1

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      10       linear         0.973333

In [47]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [51]:
model_param={
    'svm': {
        'model':SVC(gamma='auto'),
        'param':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random forest':{
        'model':RandomForestClassifier(),
        'param':{
            'n_estimators':[1,5,10]
        }
    },
    'LogisticRegression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'param':{
            'C':[1,5,10]
        }
    }
}

In [59]:
scores=[]
for model_name,mp in model_param.items():
    clf=GridSearchCV(mp['model'],mp['param'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_param':clf.best_params_
    })
scores

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_param': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random forest',
  'best_score': 0.96,
  'best_param': {'n_estimators': 10}},
 {'model': 'LogisticRegression',
  'best_score': 0.9666666666666668,
  'best_param': {'C': 5}}]

In [61]:
df=pd.DataFrame(scores)
df

model  best_score                 best_param
0                 svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1       random forest    0.960000       {'n_estimators': 10}
2  LogisticRegression    0.966667                   {'C': 5}